name: Python test
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        python-version: ["3.8", "3.12"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install poetry
        run: pip install poetry

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install project dependencies with poetry
        run: poetry install

      - name: Run tests
        run: poetry run pytest # Replace with your test command if different

      - name: Run FastAPI Application (Background)
        run: |
          poetry run uvicorn main:app --host 127.0.0.1 --port 8000 --reload

      - name: Test FastAPI Endpoint
        run: |
          curl http://127.0.0.1:8000/time