name: Python test
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --with dev

      - name: Start uvicorn
        run: |
          poetry run uvicorn main:app --host 127.0.0.1 --port 8000 --reload &
          echo $! > uvicorn.pid

      - name: Wait for uvicorn
        run: sleep 5

      - name: Run tests
        run: poetry run pytest

      - name: Stop uvicorn
        run: |
          kill $(cat uvicorn.pid)
